[package]
name = "apple-bundle"
version = "0.2.0"
authors = ["DodoRare Team <dodonotrare@gmail.com>"]
description = "Apple BundleResources serializer and deserializer for Rust"
repository = "https://github.com/dodorare/apple-bundle-rs"
license = "Apache-2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_plain = "1.0.2"
plist = { version = "1.10.0", optional = true }

[features]
default = ["plist"]

[dev-dependencies]
tempfile = "3.27.0"
