[package]
name = "apple-bundle"
version = "0.0.1"
authors = ["DodoRare Team <dodonotrare@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3"
